### PR TITLE
feat: add autocannon-compare-cli package

### PR DESCRIPTION
**Pull request by guilhermelimak**
Add a small cli utilty to compare autocannon results.

You can see a preview of the comparison here:
image

Closes nearform/hub-draft-issues#172

### CODE REVIEW

**Comment by simone-sanfratello** [comment]
Nice! I'd add the option to rename the columns, sometimes it's hard to remember which one is "a" and which one is "b" and it's convenient to have for example "current" and "next"

```
autocannon-compare-cli -a ./path-to-file-a.json -b ./path-to-file-b.json -a-as current -b-as next
```

**Review by simoneb — COMMENTED** [review]
Shall we include using this in the Web UI then?

**Comment by guilhermelimak** [comment]
> Shall we include using this in the Web UI then?

I think that's a good idea. Should make it way more easy to use that way.

**Comment by simone-sanfratello** [comment]
> Shall we include using this in the Web UI then?

That was my original request! :rocket:

**Comment by guilhermelimak** [comment]
I've updated the backend with a new route to return the new comparison, but the frontend changes are still missing.

**Comment by guilhermelimak** [comment]
This now is partially implemented on the frontend, it's using the new route and showing the results in a table but could use some improvements on styling like adding color to the results.

I kept the old compare route intact and created a `v2` using the new compare function. I'm not entirely sure if we should try to integrate both the new and old results since they carried some different info on them. If that's not desirable we could just remove the old one and remove the `v2` naming from the new one.

**Comment by simoneb** [comment]
@guilhermelimak where do we stand with this PR?

**Comment by guilhermelimak** [comment]
@simoneb should be ready for reviewing and testing, there's the point I mentioned on my previous comment about some data we had on the previous compare function and we don't have on the new one but should be good to go if that's fine

**Review by simoneb — APPROVED** [review]

**Pull request merged**
